package com.bsl.services;

import bea.jolt.pool.Result;
import com.bsl.Constants;
import com.bsl.FmlField;
import com.bsl.ServiceOutput;
import com.bsl.TypeConverter;
import com.bsl.exceptions.BSLFokusException;


/**
 * @author  Ninja - Generated by Ninja tools : created on 18-May-21 6:35:16 PM. Fokus_340_drop1
 */
public class ArGtBanOutput extends ServiceOutput {


	/**
	 * Creates a new instance of ArGtBanOutput
	 *
	 * @throws BSLFokusException
	 */
	public ArGtBanOutput(int nApplicationStatus) throws BSLFokusException {
		createFmlBuffer();
		setApplicationCode(nApplicationStatus);
	}


	public ArGtBanOutput() {}


	/**
	 * Creates a new instance of ArGtBanOutput
	 *
	 * @param ds Output dataset from Tuxedo service.
	 * @throws BSLFokusException
	 */
	public ArGtBanOutput(Result ds) throws BSLFokusException {
		createFmlBuffer();
		populateFmlBuffer(ds);
	}


	/**
	 * Populates the FML buffer.
	 *
	 * @throws BSLFokusException
	 */
	private void createFmlBuffer() throws BSLFokusException {

		fmlBuffer = new FmlField[167];


		this.fmlBuffer[0] = new FmlField("GENERATION", FmlField.TYPE_INTEGER, -1, null, 0, 1);
		this.fmlBuffer[1] = new FmlField("DIRECTIVE", FmlField.TYPE_INTEGER, -1, "0", 1, 1);
		this.fmlBuffer[2] = new FmlField("FIRST_DIRECTIVE", FmlField.TYPE_INTEGER, -1, null, 2, 1);
		this.fmlBuffer[3] = new FmlField("SECOND_DIRECTIVE", FmlField.TYPE_INTEGER, -1, null, 3, 1);
		this.fmlBuffer[4] = new FmlField("OPERATOR_ID", FmlField.TYPE_INTEGER, -1, Constants.BSL_OPERATOR.toString(), 4, 1);
		this.fmlBuffer[5] = new FmlField("APPLICATION_ID", FmlField.TYPE_STRING, 7, Constants.BSL, 5, 1);
		this.fmlBuffer[6] = new FmlField("TRANSACTION_MODE", FmlField.TYPE_BYTE, -1, "0", 6, 1);
		this.fmlBuffer[7] = new FmlField("RUN_DATE", FmlField.TYPE_STRING, 9, null, 7, 1);
		this.fmlBuffer[8] = new FmlField("MARKET_CODE", FmlField.TYPE_STRING, 4,"NTC", 8, 1);
		this.fmlBuffer[9] = new FmlField("SVC_STATUS", FmlField.TYPE_BYTE, -1, null, 9, 1);
		this.fmlBuffer[10] = new FmlField("LAST_UPDATE_DATE", FmlField.TYPE_STRING, 15, null, 10, 1);
		this.fmlBuffer[11] = new FmlField("LAST_UPDATE_STAMP", FmlField.TYPE_SHORT, -1, null, 11, 1);
		this.fmlBuffer[12] = new FmlField("ENV_CODE", FmlField.TYPE_STRING, 11, "PRDENV", 12, 1);
		this.fmlBuffer[13] = new FmlField("SESSION_ID", FmlField.TYPE_INTEGER, -1, "0", 13, 1);
		this.fmlBuffer[14] = new FmlField("ONLINE_TRX_NO", FmlField.TYPE_INTEGER, -1, "0", 14, 1);
		this.fmlBuffer[15] = new FmlField("GROUP_TRX_ID", FmlField.TYPE_INTEGER, -1, null, 15, 1);
		this.fmlBuffer[16] = new FmlField("ROWID", FmlField.TYPE_STRING, 19, null, 16, 1);
		this.fmlBuffer[17] = new FmlField("BAN", FmlField.TYPE_INTEGER, -1, null, 17, 1);
		this.fmlBuffer[18] = new FmlField("SYS_CREATION_DATE", FmlField.TYPE_STRING, 15, null, 18, 1);
		this.fmlBuffer[19] = new FmlField("SYS_UPDATE_DATE", FmlField.TYPE_STRING, 15, null, 19, 1);
		this.fmlBuffer[20] = new FmlField("PBANRECOPERATOR_ID", FmlField.TYPE_INTEGER, -1, null, 20, 1);
		this.fmlBuffer[21] = new FmlField("PBANRECAPPLICATION_ID", FmlField.TYPE_STRING, 7, null, 21, 1);
		this.fmlBuffer[22] = new FmlField("DL_SERVICE_CODE", FmlField.TYPE_STRING, 6, null, 22, 1);
		this.fmlBuffer[23] = new FmlField("DL_UPDATE_STAMP", FmlField.TYPE_SHORT, -1, null, 23, 1);
		this.fmlBuffer[24] = new FmlField("CURR_ROOT_BAN", FmlField.TYPE_INTEGER, -1, null, 24, 1);
		this.fmlBuffer[25] = new FmlField("NEXT_ROOT_BAN", FmlField.TYPE_INTEGER, -1, null, 25, 1);
		this.fmlBuffer[26] = new FmlField("PARTITION_ROOT_BAN", FmlField.TYPE_INTEGER, -1, null, 26, 1);
		this.fmlBuffer[27] = new FmlField("AR_EXCPT_ACCT_IND", FmlField.TYPE_BYTE, -1, null, 27, 1);
		this.fmlBuffer[28] = new FmlField("ACCOUNT_TYPE", FmlField.TYPE_BYTE, -1, null, 28, 1);
		this.fmlBuffer[29] = new FmlField("ACCOUNT_SUB_TYPE", FmlField.TYPE_STRING, 3, null, 29, 1);
		this.fmlBuffer[30] = new FmlField("AR_BALANCE", FmlField.TYPE_DOUBLE, -1, null, 30, 1);
		this.fmlBuffer[31] = new FmlField("BAN_STATUS", FmlField.TYPE_BYTE, -1, null, 31, 1);
		this.fmlBuffer[32] = new FmlField("HIST_LAST_DATE", FmlField.TYPE_STRING, 9, null, 32, 1);
		this.fmlBuffer[33] = new FmlField("STATUS_LAST_DATE", FmlField.TYPE_STRING, 9, null, 33, 1);
		this.fmlBuffer[34] = new FmlField("STATUS_ACTV_CODE", FmlField.TYPE_STRING, 4, null, 34, 1);
		this.fmlBuffer[35] = new FmlField("STATUS_ACTV_RSN_CODE", FmlField.TYPE_STRING, 5, null, 35, 1);
		this.fmlBuffer[36] = new FmlField("AR_WO_IND", FmlField.TYPE_BYTE, -1, null, 36, 1);
		this.fmlBuffer[37] = new FmlField("CUSTOMER_ID", FmlField.TYPE_INTEGER, -1, null, 37, 1);
		this.fmlBuffer[38] = new FmlField("START_SERVICE_DATE", FmlField.TYPE_STRING, 9, null, 38, 1);
		this.fmlBuffer[39] = new FmlField("DEFAULT_SUB_MARKET", FmlField.TYPE_STRING, 4, null, 39, 1);
		this.fmlBuffer[40] = new FmlField("DEFAULT_DEPARTMENT", FmlField.TYPE_STRING, 5, null, 40, 1);
		this.fmlBuffer[41] = new FmlField("COL_DELINQ_STATUS", FmlField.TYPE_BYTE, -1, null, 41, 1);
		this.fmlBuffer[42] = new FmlField("COL_DELINQ_STS_DATE", FmlField.TYPE_STRING, 9, null, 42, 1);
		this.fmlBuffer[43] = new FmlField("COL_WAIVER_IND", FmlField.TYPE_BYTE, -1, null, 43, 1);
		this.fmlBuffer[44] = new FmlField("COL_WAIVER_DATE", FmlField.TYPE_STRING, 9, null, 44, 1);
		this.fmlBuffer[45] = new FmlField("COL_WAIVER_UID", FmlField.TYPE_STRING, 9, null, 45, 1);
		this.fmlBuffer[46] = new FmlField("COL_CATEGORY_NO", FmlField.TYPE_SHORT, -1, null, 46, 1);
		this.fmlBuffer[47] = new FmlField("COL_PATH_CODE", FmlField.TYPE_STRING, 4, null, 47, 1);
		this.fmlBuffer[48] = new FmlField("COL_NEXT_STEP_NO", FmlField.TYPE_SHORT, -1, null, 48, 1);
		this.fmlBuffer[49] = new FmlField("COL_NEXT_STEP_DATE", FmlField.TYPE_STRING, 9, null, 49, 1);
		this.fmlBuffer[50] = new FmlField("COL_NEXT_STP_APR_COD", FmlField.TYPE_BYTE, -1, null, 50, 1);
		this.fmlBuffer[51] = new FmlField("COL_NEXT_STP_APR_COL", FmlField.TYPE_STRING, 9, null, 51, 1);
		this.fmlBuffer[52] = new FmlField("COL_ASSIGNED_COLL", FmlField.TYPE_STRING, 9, null, 52, 1);
		this.fmlBuffer[53] = new FmlField("COL_COLCT_ASD_DATE", FmlField.TYPE_STRING, 9, null, 53, 1);
		this.fmlBuffer[54] = new FmlField("COL_AGNCY_CODE", FmlField.TYPE_STRING, 9, null, 54, 1);
		this.fmlBuffer[55] = new FmlField("COL_AGNCY_ASD_DATE", FmlField.TYPE_STRING, 9, null, 55, 1);
		this.fmlBuffer[56] = new FmlField("COL_AGNCY_ASD_AMT", FmlField.TYPE_DOUBLE, -1, null, 56, 1);
		this.fmlBuffer[57] = new FmlField("COL_FIRST_CNTCT_DATE", FmlField.TYPE_STRING, 9, null, 57, 1);
		this.fmlBuffer[58] = new FmlField("COL_CODE", FmlField.TYPE_BYTE, -1, null, 58, 1);
		this.fmlBuffer[59] = new FmlField("COMP_CRD_LMT", FmlField.TYPE_DOUBLE, -1, null, 59, 1);
		this.fmlBuffer[60] = new FmlField("EQU_CRD_LMT", FmlField.TYPE_DOUBLE, -1, null, 60, 1);
		this.fmlBuffer[61] = new FmlField("COL_FIXED_PATH", FmlField.TYPE_STRING, 4, null, 61, 1);
		this.fmlBuffer[62] = new FmlField("CREDIT_DATE", FmlField.TYPE_STRING, 15, null, 62, 1);
		this.fmlBuffer[63] = new FmlField("CREDIT_SOURCE", FmlField.TYPE_BYTE, -1, null, 63, 1);
		this.fmlBuffer[64] = new FmlField("CREDIT_STATUS", FmlField.TYPE_STRING, 3, null, 64, 1);
		this.fmlBuffer[65] = new FmlField("CREDIT_CLASS", FmlField.TYPE_BYTE, -1, null, 65, 1);
		this.fmlBuffer[66] = new FmlField("BILL_CYCLE", FmlField.TYPE_SHORT, -1, null, 66, 1);
		this.fmlBuffer[67] = new FmlField("BL_CUR_BILL_SEQ_NO", FmlField.TYPE_SHORT, -1, null, 67, 1);
		this.fmlBuffer[68] = new FmlField("BL_LAST_PROD_DATE", FmlField.TYPE_STRING, 9, null, 68, 1);
		this.fmlBuffer[69] = new FmlField("BL_VAT_EXEMPT_IND", FmlField.TYPE_BYTE, -1, null, 69, 1);
		this.fmlBuffer[70] = new FmlField("BL_VAT_EXEMPT_DATE", FmlField.TYPE_STRING, 9, null, 70, 1);
		this.fmlBuffer[71] = new FmlField("BL_VAT_EXEMPT_REF_NO", FmlField.TYPE_STRING, 17, null, 71, 1);
		this.fmlBuffer[72] = new FmlField("BL_VAT_EXEMPT_RSN_CD", FmlField.TYPE_STRING, 4, null, 72, 1);
		this.fmlBuffer[73] = new FmlField("BL_LAST_CYC_RUN_YEAR", FmlField.TYPE_SHORT, -1, null, 73, 1);
		this.fmlBuffer[74] = new FmlField("BL_LAST_CYC_RUN_MNTH", FmlField.TYPE_SHORT, -1, null, 74, 1);
		this.fmlBuffer[75] = new FmlField("BL_LAST_CYC_CODE", FmlField.TYPE_SHORT, -1, null, 75, 1);
		this.fmlBuffer[76] = new FmlField("BL_LAST_RG_BL_SEQ_NO", FmlField.TYPE_SHORT, -1, null, 76, 1);
		this.fmlBuffer[77] = new FmlField("BL_LAST_RG_CYC_DATE", FmlField.TYPE_STRING, 9, null, 77, 1);
		this.fmlBuffer[78] = new FmlField("BL_COMPLT_STATUS", FmlField.TYPE_BYTE, -1, null, 78, 1);
		this.fmlBuffer[79] = new FmlField("BL_COMPLT_DATE", FmlField.TYPE_STRING, 9, null, 79, 1);
		this.fmlBuffer[80] = new FmlField("BL_SPECIAL_CYCLE", FmlField.TYPE_SHORT, -1, null, 80, 1);
		this.fmlBuffer[81] = new FmlField("BL_SPECL_CYCL_TYPE", FmlField.TYPE_BYTE, -1, null, 81, 1);
		this.fmlBuffer[82] = new FmlField("BL_PRT_CATEGORY", FmlField.TYPE_STRING, 3, null, 82, 1);
		this.fmlBuffer[83] = new FmlField("BL_ZERO_BALANC_IND", FmlField.TYPE_BYTE, -1, null, 83, 1);
		this.fmlBuffer[84] = new FmlField("BL_MAN_HNDL_RSN", FmlField.TYPE_STRING, 3, null, 84, 1);
		this.fmlBuffer[85] = new FmlField("BL_MAN_HNDL_EFF_DATE", FmlField.TYPE_STRING, 9, null, 85, 1);
		this.fmlBuffer[86] = new FmlField("BL_MAN_HNDL_EXP_DATE", FmlField.TYPE_STRING, 9, null, 86, 1);
		this.fmlBuffer[87] = new FmlField("BL_MAN_HNDL_REQ_OPID", FmlField.TYPE_INTEGER, -1, null, 87, 1);
		this.fmlBuffer[88] = new FmlField("BL_MAN_HNDL_BY_OPID", FmlField.TYPE_INTEGER, -1, null, 88, 1);
		this.fmlBuffer[89] = new FmlField("BL_REQ_ST_GRACE_PRD", FmlField.TYPE_STRING, 9, null, 89, 1);
		this.fmlBuffer[90] = new FmlField("BL_REQ_END_GRACE_PRD", FmlField.TYPE_STRING, 9, null, 90, 1);
		this.fmlBuffer[91] = new FmlField("BL_NEXT_CYCLE", FmlField.TYPE_SHORT, -1, null, 91, 1);
		this.fmlBuffer[92] = new FmlField("BL_NEXT_CYC_EFF_DATE", FmlField.TYPE_STRING, 9, null, 92, 1);
		this.fmlBuffer[93] = new FmlField("BL_SUSP_RC_RATE_TYPE", FmlField.TYPE_BYTE, -1, null, 93, 1);
		this.fmlBuffer[94] = new FmlField("BL_DEF_MAILING_IND", FmlField.TYPE_BYTE, -1, null, 94, 1);
		this.fmlBuffer[95] = new FmlField("BL_BILL_PROD_IND", FmlField.TYPE_BYTE, -1, null, 95, 1);
		this.fmlBuffer[96] = new FmlField("BL_BAL_HANDLE_IND", FmlField.TYPE_BYTE, -1, null, 96, 1);
		this.fmlBuffer[97] = new FmlField("BL_UD_LST_PROD_DATE", FmlField.TYPE_STRING, 9, null, 97, 1);
		this.fmlBuffer[98] = new FmlField("BL_UD_LST_CYC_RUN_YR", FmlField.TYPE_SHORT, -1, null, 98, 1);
		this.fmlBuffer[99] = new FmlField("BL_UD_LST_CYC_RUN_MN", FmlField.TYPE_SHORT, -1, null, 99, 1);
		this.fmlBuffer[100] = new FmlField("BL_UD_LST_RG_BL_SEQNO", FmlField.TYPE_SHORT, -1, null, 100, 1);
		this.fmlBuffer[101] = new FmlField("BL_UD_LST_RG_CYC_DATE", FmlField.TYPE_STRING, 9, null, 101, 1);
		this.fmlBuffer[102] = new FmlField("BL_UD_LST_CYC_CD", FmlField.TYPE_SHORT, -1, null, 102, 1);
		this.fmlBuffer[103] = new FmlField("BL_UD_SPCL_CYC", FmlField.TYPE_SHORT, -1, null, 103, 1);
		this.fmlBuffer[104] = new FmlField("BL_UD_SPCL_CYC_TYPE", FmlField.TYPE_BYTE, -1, null, 104, 1);
		this.fmlBuffer[105] = new FmlField("BL_NO_MNSP_IND", FmlField.TYPE_BYTE, -1, null, 105, 1);
		this.fmlBuffer[106] = new FmlField("BL_LST_BAN_DIS_DT", FmlField.TYPE_STRING, 9, null, 106, 1);
		this.fmlBuffer[107] = new FmlField("BL_LST_HIER_DIS_DT", FmlField.TYPE_STRING, 9, null, 107, 1);
		this.fmlBuffer[108] = new FmlField("BL_LST_TREE_DIS_DT", FmlField.TYPE_STRING, 9, null, 108, 1);
		this.fmlBuffer[109] = new FmlField("BL_LST_BAN_DIS_DT_U", FmlField.TYPE_STRING, 9, null, 109, 1);
		this.fmlBuffer[110] = new FmlField("BL_LST_HIER_DIS_DT_U", FmlField.TYPE_STRING, 9, null, 110, 1);
		this.fmlBuffer[111] = new FmlField("BL_LST_TREE_DIS_DT_U", FmlField.TYPE_STRING, 9, null, 111, 1);
		this.fmlBuffer[112] = new FmlField("BL_LST_BAN_DIS_SN", FmlField.TYPE_SHORT, -1, null, 112, 1);
		this.fmlBuffer[113] = new FmlField("BL_LST_HIER_DIS_SN", FmlField.TYPE_SHORT, -1, null, 113, 1);
		this.fmlBuffer[114] = new FmlField("BL_LST_TREE_DIS_SN", FmlField.TYPE_SHORT, -1, null, 114, 1);
		this.fmlBuffer[115] = new FmlField("BL_LST_BAN_DIS_SN_U", FmlField.TYPE_SHORT, -1, null, 115, 1);
		this.fmlBuffer[116] = new FmlField("BL_LST_HIER_DIS_SN_U", FmlField.TYPE_SHORT, -1, null, 116, 1);
		this.fmlBuffer[117] = new FmlField("BL_LST_TREE_DIS_SN_U", FmlField.TYPE_SHORT, -1, null, 117, 1);
		this.fmlBuffer[118] = new FmlField("BL_HIER_BAN_IND", FmlField.TYPE_BYTE, -1, null, 118, 1);
		this.fmlBuffer[119] = new FmlField("BL_DUE_DAY", FmlField.TYPE_SHORT, -1, null, 119, 1);
		this.fmlBuffer[120] = new FmlField("BL_PREPAYMENT_IND", FmlField.TYPE_BYTE, -1, null, 120, 1);
		this.fmlBuffer[121] = new FmlField("BLACK_LISTED_IND", FmlField.TYPE_BYTE, -1, null, 121, 1);
		this.fmlBuffer[122] = new FmlField("VIP_IND", FmlField.TYPE_BYTE, -1, null, 122, 1);
		this.fmlBuffer[123] = new FmlField("ORG_CODE", FmlField.TYPE_STRING, 10, null, 123, 1);
		this.fmlBuffer[124] = new FmlField("CYCLE_FREQUENCY", FmlField.TYPE_SHORT, -1, null, 124, 1);
		this.fmlBuffer[125] = new FmlField("CYCLE_FIRST_BILL_MONTH", FmlField.TYPE_SHORT, -1, null, 125, 1);
		this.fmlBuffer[126] = new FmlField("EDI_LOCATION_NUMBER", FmlField.TYPE_DOUBLE, -1, null, 126, 1);
		this.fmlBuffer[127] = new FmlField("CS_MIN_REQ_CTNS", FmlField.TYPE_INTEGER, -1, null, 127, 1);
		this.fmlBuffer[128] = new FmlField("CS_PEN_PER_MISS_CTN", FmlField.TYPE_DOUBLE, -1, null, 128, 1);
		this.fmlBuffer[129] = new FmlField("CS_COM_START_DATE", FmlField.TYPE_STRING, 9, null, 129, 1);
		this.fmlBuffer[130] = new FmlField("CS_COM_END_DATE", FmlField.TYPE_STRING, 9, null, 130, 1);
		this.fmlBuffer[131] = new FmlField("CS_COM_REASON_CODE", FmlField.TYPE_STRING, 4, null, 131, 1);
		this.fmlBuffer[132] = new FmlField("CS_COM_ORIG_NO_MONTH", FmlField.TYPE_SHORT, -1, null, 132, 1);
		this.fmlBuffer[133] = new FmlField("CS_FOLLOW_UPS_STATE", FmlField.TYPE_STRING, 4, null, 133, 1);
		this.fmlBuffer[134] = new FmlField("CS_SPEC_MEMO_IND", FmlField.TYPE_BYTE, -1, null, 134, 1);
		this.fmlBuffer[135] = new FmlField("STATUS_ISSUE_DATE", FmlField.TYPE_STRING, 9, null, 135, 1);
		this.fmlBuffer[136] = new FmlField("CS_BAN_TRX_OFF_IND", FmlField.TYPE_BYTE, -1, null, 136, 1);
		this.fmlBuffer[137] = new FmlField("CS_HANDLE_BY_CTN_IND", FmlField.TYPE_BYTE, -1, null, 137, 1);
		this.fmlBuffer[138] = new FmlField("CS_LOCK_MECHANISM", FmlField.TYPE_BYTE, -1, null, 138, 1);
		this.fmlBuffer[139] = new FmlField("CS_DEF_PRODUCT_TYPE", FmlField.TYPE_STRING, 4, null, 139, 1);
		this.fmlBuffer[140] = new FmlField("CAS_DEP_AMT_PER_CTN", FmlField.TYPE_DOUBLE, -1, null, 140, 1);
		this.fmlBuffer[141] = new FmlField("CONV_RUN_NO", FmlField.TYPE_SHORT, -1, null, 141, 1);
		this.fmlBuffer[142] = new FmlField("CARRY_OVER_BILL", FmlField.TYPE_BYTE, -1, null, 142, 1);
		this.fmlBuffer[143] = new FmlField("OLD_ACCOUNT_ID", FmlField.TYPE_STRING, 21, null, 143, 1);
		this.fmlBuffer[144] = new FmlField("HIDE_PHONE_DIGITS_IND", FmlField.TYPE_BYTE, -1, null, 144, 1);
		this.fmlBuffer[145] = new FmlField("SEC_DEPARTMENT", FmlField.TYPE_STRING, 5, null, 145, 1);
		this.fmlBuffer[146] = new FmlField("PAYABLE_LTR_SEND_DATE", FmlField.TYPE_STRING, 9, null, 146, 1);
		this.fmlBuffer[147] = new FmlField("NEXT_CONF_ROOT_BAN", FmlField.TYPE_INTEGER, -1, null, 147, 1);
		this.fmlBuffer[148] = new FmlField("LAST_CONF_DATE", FmlField.TYPE_STRING, 9, null, 148, 1);
		this.fmlBuffer[149] = new FmlField("ALLOW_ADVERTISING_IND", FmlField.TYPE_BYTE, -1, null, 149, 1);
		this.fmlBuffer[150] = new FmlField("AGENCY_REF_NO", FmlField.TYPE_STRING, 9, null, 150, 1);
		this.fmlBuffer[151] = new FmlField("COL_AGENCY_CONF_DT", FmlField.TYPE_STRING, 9, null, 151, 1);
		this.fmlBuffer[152] = new FmlField("BAN_GROUP_NO", FmlField.TYPE_STRING, 11, null, 152, 1);
		this.fmlBuffer[153] = new FmlField("CAAP_TYPE", FmlField.TYPE_BYTE, -1, null, 153, 1);
		this.fmlBuffer[154] = new FmlField("BAN_FF_EXP_DATE", FmlField.TYPE_STRING, 15, null, 154, 1);
		this.fmlBuffer[155] = new FmlField("UNBILLED_REVENUE", FmlField.TYPE_DOUBLE, -1, null, 155, 1);
		this.fmlBuffer[156] = new FmlField("LAST_AGNCY_UPDATE", FmlField.TYPE_STRING, 9, null, 156, 1);
		this.fmlBuffer[157] = new FmlField("WAIVER_RSN_CODE", FmlField.TYPE_STRING, 7, null, 157, 1);
		this.fmlBuffer[158] = new FmlField("COL_WAIVER_EXP_DATE", FmlField.TYPE_STRING, 9, null, 158, 1);
		this.fmlBuffer[159] = new FmlField("INVOICE_FEE_WAIVE_IND", FmlField.TYPE_BYTE, -1, null, 159, 1);
		this.fmlBuffer[160] = new FmlField("PRD_ZERO_RATE_BILL", FmlField.TYPE_BYTE, -1, null, 160, 1);
		this.fmlBuffer[161] = new FmlField("BL_INV_SEQ_NO", FmlField.TYPE_SHORT, -1, null, 161, 1);
		this.fmlBuffer[162] = new FmlField("BRAND_ID", FmlField.TYPE_BYTE, -1, null, 162, 1);
		this.fmlBuffer[163] = new FmlField("HELD_SUB_LETTER_IND", FmlField.TYPE_BYTE, -1, null, 163, 1);
		this.fmlBuffer[164] = new FmlField("HELD_SUB_LTR_EXP_DATE", FmlField.TYPE_STRING, 9, null, 164, 1);
		this.fmlBuffer[165] = new FmlField("CURRENCY_TYPE", FmlField.TYPE_STRING, 4, null, 165, 1);
		this.fmlBuffer[166] = new FmlField("COUNTERPART_ID", FmlField.TYPE_STRING, 4, null, 166, 1);
	} // End of constractor

	public Integer get_GENERATION() throws BSLFokusException { return ((Integer) this.fmlBuffer[0].getValue(0)); }
	public void set_GENERATION(Integer value) throws BSLFokusException { this.fmlBuffer[0].setValue(0, value); }


	public Integer get_DIRECTIVE() throws BSLFokusException { return ((Integer) this.fmlBuffer[1].getValue(0)); }
	public void set_DIRECTIVE(Integer value) throws BSLFokusException { this.fmlBuffer[1].setValue(0, value); }


	public Integer get_FIRST_DIRECTIVE() throws BSLFokusException { return ((Integer) this.fmlBuffer[2].getValue(0)); }
	public void set_FIRST_DIRECTIVE(Integer value) throws BSLFokusException { this.fmlBuffer[2].setValue(0, value); }


	public Integer get_SECOND_DIRECTIVE() throws BSLFokusException { return ((Integer) this.fmlBuffer[3].getValue(0)); }
	public void set_SECOND_DIRECTIVE(Integer value) throws BSLFokusException { this.fmlBuffer[3].setValue(0, value); }


	public Integer get_OPERATOR_ID() throws BSLFokusException { return ((Integer) this.fmlBuffer[4].getValue(0)); }
	public void set_OPERATOR_ID(Integer value) throws BSLFokusException { this.fmlBuffer[4].setValue(0, value); }


	public String get_APPLICATION_ID() throws BSLFokusException { return ((String) this.fmlBuffer[5].getValue(0)); }
	public void set_APPLICATION_ID(String value) throws BSLFokusException { this.fmlBuffer[5].setValue(0, value); }


	public String get_TRANSACTION_MODE() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[6].getValue(0))); }
	public void set_TRANSACTION_MODE(String value) throws BSLFokusException { this.fmlBuffer[6].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_RUN_DATE() throws BSLFokusException { return ((String) this.fmlBuffer[7].getValue(0)); }
	public void set_RUN_DATE(String value) throws BSLFokusException { this.fmlBuffer[7].setValue(0, value); }


	public String get_MARKET_CODE() throws BSLFokusException { return ((String) this.fmlBuffer[8].getValue(0)); }
	public void set_MARKET_CODE(String value) throws BSLFokusException { this.fmlBuffer[8].setValue(0, value); }


	public String get_SVC_STATUS() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[9].getValue(0))); }
	public void set_SVC_STATUS(String value) throws BSLFokusException { this.fmlBuffer[9].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_LAST_UPDATE_DATE() throws BSLFokusException { return ((String) this.fmlBuffer[10].getValue(0)); }
	public void set_LAST_UPDATE_DATE(String value) throws BSLFokusException { this.fmlBuffer[10].setValue(0, value); }


	public Integer get_LAST_UPDATE_STAMP() throws BSLFokusException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[11].getValue(0))); }
	public void set_LAST_UPDATE_STAMP(Integer value) throws BSLFokusException { this.fmlBuffer[11].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_ENV_CODE() throws BSLFokusException { return ((String) this.fmlBuffer[12].getValue(0)); }
	public void set_ENV_CODE(String value) throws BSLFokusException { this.fmlBuffer[12].setValue(0, value); }


	public Integer get_SESSION_ID() throws BSLFokusException { return ((Integer) this.fmlBuffer[13].getValue(0)); }
	public void set_SESSION_ID(Integer value) throws BSLFokusException { this.fmlBuffer[13].setValue(0, value); }


	public Integer get_ONLINE_TRX_NO() throws BSLFokusException { return ((Integer) this.fmlBuffer[14].getValue(0)); }
	public void set_ONLINE_TRX_NO(Integer value) throws BSLFokusException { this.fmlBuffer[14].setValue(0, value); }


	public Integer get_GROUP_TRX_ID() throws BSLFokusException { return ((Integer) this.fmlBuffer[15].getValue(0)); }
	public void set_GROUP_TRX_ID(Integer value) throws BSLFokusException { this.fmlBuffer[15].setValue(0, value); }


	public String get_ROWID() throws BSLFokusException { return ((String) this.fmlBuffer[16].getValue(0)); }
	public void set_ROWID(String value) throws BSLFokusException { this.fmlBuffer[16].setValue(0, value); }


	public Integer get_BAN() throws BSLFokusException { return ((Integer) this.fmlBuffer[17].getValue(0)); }
	public void set_BAN(Integer value) throws BSLFokusException { this.fmlBuffer[17].setValue(0, value); }


	public String get_SYS_CREATION_DATE() throws BSLFokusException { return ((String) this.fmlBuffer[18].getValue(0)); }
	public void set_SYS_CREATION_DATE(String value) throws BSLFokusException { this.fmlBuffer[18].setValue(0, value); }


	public String get_SYS_UPDATE_DATE() throws BSLFokusException { return ((String) this.fmlBuffer[19].getValue(0)); }
	public void set_SYS_UPDATE_DATE(String value) throws BSLFokusException { this.fmlBuffer[19].setValue(0, value); }


	public Integer get_PBANRECOPERATOR_ID() throws BSLFokusException { return ((Integer) this.fmlBuffer[20].getValue(0)); }
	public void set_PBANRECOPERATOR_ID(Integer value) throws BSLFokusException { this.fmlBuffer[20].setValue(0, value); }


	public String get_PBANRECAPPLICATION_ID() throws BSLFokusException { return ((String) this.fmlBuffer[21].getValue(0)); }
	public void set_PBANRECAPPLICATION_ID(String value) throws BSLFokusException { this.fmlBuffer[21].setValue(0, value); }


	public String get_DL_SERVICE_CODE() throws BSLFokusException { return ((String) this.fmlBuffer[22].getValue(0)); }
	public void set_DL_SERVICE_CODE(String value) throws BSLFokusException { this.fmlBuffer[22].setValue(0, value); }


	public Integer get_DL_UPDATE_STAMP() throws BSLFokusException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[23].getValue(0))); }
	public void set_DL_UPDATE_STAMP(Integer value) throws BSLFokusException { this.fmlBuffer[23].setValue(0, TypeConverter.integerToShort(value)); }


	public Integer get_CURR_ROOT_BAN() throws BSLFokusException { return ((Integer) this.fmlBuffer[24].getValue(0)); }
	public void set_CURR_ROOT_BAN(Integer value) throws BSLFokusException { this.fmlBuffer[24].setValue(0, value); }


	public Integer get_NEXT_ROOT_BAN() throws BSLFokusException { return ((Integer) this.fmlBuffer[25].getValue(0)); }
	public void set_NEXT_ROOT_BAN(Integer value) throws BSLFokusException { this.fmlBuffer[25].setValue(0, value); }


	public Integer get_PARTITION_ROOT_BAN() throws BSLFokusException { return ((Integer) this.fmlBuffer[26].getValue(0)); }
	public void set_PARTITION_ROOT_BAN(Integer value) throws BSLFokusException { this.fmlBuffer[26].setValue(0, value); }


	public String get_AR_EXCPT_ACCT_IND() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[27].getValue(0))); }
	public void set_AR_EXCPT_ACCT_IND(String value) throws BSLFokusException { this.fmlBuffer[27].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_ACCOUNT_TYPE() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[28].getValue(0))); }
	public void set_ACCOUNT_TYPE(String value) throws BSLFokusException { this.fmlBuffer[28].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_ACCOUNT_SUB_TYPE() throws BSLFokusException { return ((String) this.fmlBuffer[29].getValue(0)); }
	public void set_ACCOUNT_SUB_TYPE(String value) throws BSLFokusException { this.fmlBuffer[29].setValue(0, value); }


	public Double get_AR_BALANCE() throws BSLFokusException { return ((Double) this.fmlBuffer[30].getValue(0)); }
	public void set_AR_BALANCE(Double value) throws BSLFokusException { this.fmlBuffer[30].setValue(0, value); }


	public String get_BAN_STATUS() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[31].getValue(0))); }
	public void set_BAN_STATUS(String value) throws BSLFokusException { this.fmlBuffer[31].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_HIST_LAST_DATE() throws BSLFokusException { return ((String) this.fmlBuffer[32].getValue(0)); }
	public void set_HIST_LAST_DATE(String value) throws BSLFokusException { this.fmlBuffer[32].setValue(0, value); }


	public String get_STATUS_LAST_DATE() throws BSLFokusException { return ((String) this.fmlBuffer[33].getValue(0)); }
	public void set_STATUS_LAST_DATE(String value) throws BSLFokusException { this.fmlBuffer[33].setValue(0, value); }


	public String get_STATUS_ACTV_CODE() throws BSLFokusException { return ((String) this.fmlBuffer[34].getValue(0)); }
	public void set_STATUS_ACTV_CODE(String value) throws BSLFokusException { this.fmlBuffer[34].setValue(0, value); }


	public String get_STATUS_ACTV_RSN_CODE() throws BSLFokusException { return ((String) this.fmlBuffer[35].getValue(0)); }
	public void set_STATUS_ACTV_RSN_CODE(String value) throws BSLFokusException { this.fmlBuffer[35].setValue(0, value); }


	public String get_AR_WO_IND() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[36].getValue(0))); }
	public void set_AR_WO_IND(String value) throws BSLFokusException { this.fmlBuffer[36].setValue(0, TypeConverter.stringToByte(value)); }


	public Integer get_CUSTOMER_ID() throws BSLFokusException { return ((Integer) this.fmlBuffer[37].getValue(0)); }
	public void set_CUSTOMER_ID(Integer value) throws BSLFokusException { this.fmlBuffer[37].setValue(0, value); }


	public String get_START_SERVICE_DATE() throws BSLFokusException { return ((String) this.fmlBuffer[38].getValue(0)); }
	public void set_START_SERVICE_DATE(String value) throws BSLFokusException { this.fmlBuffer[38].setValue(0, value); }


	public String get_DEFAULT_SUB_MARKET() throws BSLFokusException { return ((String) this.fmlBuffer[39].getValue(0)); }
	public void set_DEFAULT_SUB_MARKET(String value) throws BSLFokusException { this.fmlBuffer[39].setValue(0, value); }


	public String get_DEFAULT_DEPARTMENT() throws BSLFokusException { return ((String) this.fmlBuffer[40].getValue(0)); }
	public void set_DEFAULT_DEPARTMENT(String value) throws BSLFokusException { this.fmlBuffer[40].setValue(0, value); }


	public String get_COL_DELINQ_STATUS() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[41].getValue(0))); }
	public void set_COL_DELINQ_STATUS(String value) throws BSLFokusException { this.fmlBuffer[41].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_COL_DELINQ_STS_DATE() throws BSLFokusException { return ((String) this.fmlBuffer[42].getValue(0)); }
	public void set_COL_DELINQ_STS_DATE(String value) throws BSLFokusException { this.fmlBuffer[42].setValue(0, value); }


	public String get_COL_WAIVER_IND() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[43].getValue(0))); }
	public void set_COL_WAIVER_IND(String value) throws BSLFokusException { this.fmlBuffer[43].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_COL_WAIVER_DATE() throws BSLFokusException { return ((String) this.fmlBuffer[44].getValue(0)); }
	public void set_COL_WAIVER_DATE(String value) throws BSLFokusException { this.fmlBuffer[44].setValue(0, value); }


	public String get_COL_WAIVER_UID() throws BSLFokusException { return ((String) this.fmlBuffer[45].getValue(0)); }
	public void set_COL_WAIVER_UID(String value) throws BSLFokusException { this.fmlBuffer[45].setValue(0, value); }


	public Integer get_COL_CATEGORY_NO() throws BSLFokusException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[46].getValue(0))); }
	public void set_COL_CATEGORY_NO(Integer value) throws BSLFokusException { this.fmlBuffer[46].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_COL_PATH_CODE() throws BSLFokusException { return ((String) this.fmlBuffer[47].getValue(0)); }
	public void set_COL_PATH_CODE(String value) throws BSLFokusException { this.fmlBuffer[47].setValue(0, value); }


	public Integer get_COL_NEXT_STEP_NO() throws BSLFokusException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[48].getValue(0))); }
	public void set_COL_NEXT_STEP_NO(Integer value) throws BSLFokusException { this.fmlBuffer[48].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_COL_NEXT_STEP_DATE() throws BSLFokusException { return ((String) this.fmlBuffer[49].getValue(0)); }
	public void set_COL_NEXT_STEP_DATE(String value) throws BSLFokusException { this.fmlBuffer[49].setValue(0, value); }


	public String get_COL_NEXT_STP_APR_COD() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[50].getValue(0))); }
	public void set_COL_NEXT_STP_APR_COD(String value) throws BSLFokusException { this.fmlBuffer[50].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_COL_NEXT_STP_APR_COL() throws BSLFokusException { return ((String) this.fmlBuffer[51].getValue(0)); }
	public void set_COL_NEXT_STP_APR_COL(String value) throws BSLFokusException { this.fmlBuffer[51].setValue(0, value); }


	public String get_COL_ASSIGNED_COLL() throws BSLFokusException { return ((String) this.fmlBuffer[52].getValue(0)); }
	public void set_COL_ASSIGNED_COLL(String value) throws BSLFokusException { this.fmlBuffer[52].setValue(0, value); }


	public String get_COL_COLCT_ASD_DATE() throws BSLFokusException { return ((String) this.fmlBuffer[53].getValue(0)); }
	public void set_COL_COLCT_ASD_DATE(String value) throws BSLFokusException { this.fmlBuffer[53].setValue(0, value); }


	public String get_COL_AGNCY_CODE() throws BSLFokusException { return ((String) this.fmlBuffer[54].getValue(0)); }
	public void set_COL_AGNCY_CODE(String value) throws BSLFokusException { this.fmlBuffer[54].setValue(0, value); }


	public String get_COL_AGNCY_ASD_DATE() throws BSLFokusException { return ((String) this.fmlBuffer[55].getValue(0)); }
	public void set_COL_AGNCY_ASD_DATE(String value) throws BSLFokusException { this.fmlBuffer[55].setValue(0, value); }


	public Double get_COL_AGNCY_ASD_AMT() throws BSLFokusException { return ((Double) this.fmlBuffer[56].getValue(0)); }
	public void set_COL_AGNCY_ASD_AMT(Double value) throws BSLFokusException { this.fmlBuffer[56].setValue(0, value); }


	public String get_COL_FIRST_CNTCT_DATE() throws BSLFokusException { return ((String) this.fmlBuffer[57].getValue(0)); }
	public void set_COL_FIRST_CNTCT_DATE(String value) throws BSLFokusException { this.fmlBuffer[57].setValue(0, value); }


	public String get_COL_CODE() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[58].getValue(0))); }
	public void set_COL_CODE(String value) throws BSLFokusException { this.fmlBuffer[58].setValue(0, TypeConverter.stringToByte(value)); }


	public Double get_COMP_CRD_LMT() throws BSLFokusException { return ((Double) this.fmlBuffer[59].getValue(0)); }
	public void set_COMP_CRD_LMT(Double value) throws BSLFokusException { this.fmlBuffer[59].setValue(0, value); }


	public Double get_EQU_CRD_LMT() throws BSLFokusException { return ((Double) this.fmlBuffer[60].getValue(0)); }
	public void set_EQU_CRD_LMT(Double value) throws BSLFokusException { this.fmlBuffer[60].setValue(0, value); }


	public String get_COL_FIXED_PATH() throws BSLFokusException { return ((String) this.fmlBuffer[61].getValue(0)); }
	public void set_COL_FIXED_PATH(String value) throws BSLFokusException { this.fmlBuffer[61].setValue(0, value); }


	public String get_CREDIT_DATE() throws BSLFokusException { return ((String) this.fmlBuffer[62].getValue(0)); }
	public void set_CREDIT_DATE(String value) throws BSLFokusException { this.fmlBuffer[62].setValue(0, value); }


	public String get_CREDIT_SOURCE() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[63].getValue(0))); }
	public void set_CREDIT_SOURCE(String value) throws BSLFokusException { this.fmlBuffer[63].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_CREDIT_STATUS() throws BSLFokusException { return ((String) this.fmlBuffer[64].getValue(0)); }
	public void set_CREDIT_STATUS(String value) throws BSLFokusException { this.fmlBuffer[64].setValue(0, value); }


	public String get_CREDIT_CLASS() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[65].getValue(0))); }
	public void set_CREDIT_CLASS(String value) throws BSLFokusException { this.fmlBuffer[65].setValue(0, TypeConverter.stringToByte(value)); }


	public Integer get_BILL_CYCLE() throws BSLFokusException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[66].getValue(0))); }
	public void set_BILL_CYCLE(Integer value) throws BSLFokusException { this.fmlBuffer[66].setValue(0, TypeConverter.integerToShort(value)); }


	public Integer get_BL_CUR_BILL_SEQ_NO() throws BSLFokusException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[67].getValue(0))); }
	public void set_BL_CUR_BILL_SEQ_NO(Integer value) throws BSLFokusException { this.fmlBuffer[67].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_BL_LAST_PROD_DATE() throws BSLFokusException { return ((String) this.fmlBuffer[68].getValue(0)); }
	public void set_BL_LAST_PROD_DATE(String value) throws BSLFokusException { this.fmlBuffer[68].setValue(0, value); }


	public String get_BL_VAT_EXEMPT_IND() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[69].getValue(0))); }
	public void set_BL_VAT_EXEMPT_IND(String value) throws BSLFokusException { this.fmlBuffer[69].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_BL_VAT_EXEMPT_DATE() throws BSLFokusException { return ((String) this.fmlBuffer[70].getValue(0)); }
	public void set_BL_VAT_EXEMPT_DATE(String value) throws BSLFokusException { this.fmlBuffer[70].setValue(0, value); }


	public String get_BL_VAT_EXEMPT_REF_NO() throws BSLFokusException { return ((String) this.fmlBuffer[71].getValue(0)); }
	public void set_BL_VAT_EXEMPT_REF_NO(String value) throws BSLFokusException { this.fmlBuffer[71].setValue(0, value); }


	public String get_BL_VAT_EXEMPT_RSN_CD() throws BSLFokusException { return ((String) this.fmlBuffer[72].getValue(0)); }
	public void set_BL_VAT_EXEMPT_RSN_CD(String value) throws BSLFokusException { this.fmlBuffer[72].setValue(0, value); }


	public Integer get_BL_LAST_CYC_RUN_YEAR() throws BSLFokusException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[73].getValue(0))); }
	public void set_BL_LAST_CYC_RUN_YEAR(Integer value) throws BSLFokusException { this.fmlBuffer[73].setValue(0, TypeConverter.integerToShort(value)); }


	public Integer get_BL_LAST_CYC_RUN_MNTH() throws BSLFokusException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[74].getValue(0))); }
	public void set_BL_LAST_CYC_RUN_MNTH(Integer value) throws BSLFokusException { this.fmlBuffer[74].setValue(0, TypeConverter.integerToShort(value)); }


	public Integer get_BL_LAST_CYC_CODE() throws BSLFokusException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[75].getValue(0))); }
	public void set_BL_LAST_CYC_CODE(Integer value) throws BSLFokusException { this.fmlBuffer[75].setValue(0, TypeConverter.integerToShort(value)); }


	public Integer get_BL_LAST_RG_BL_SEQ_NO() throws BSLFokusException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[76].getValue(0))); }
	public void set_BL_LAST_RG_BL_SEQ_NO(Integer value) throws BSLFokusException { this.fmlBuffer[76].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_BL_LAST_RG_CYC_DATE() throws BSLFokusException { return ((String) this.fmlBuffer[77].getValue(0)); }
	public void set_BL_LAST_RG_CYC_DATE(String value) throws BSLFokusException { this.fmlBuffer[77].setValue(0, value); }


	public String get_BL_COMPLT_STATUS() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[78].getValue(0))); }
	public void set_BL_COMPLT_STATUS(String value) throws BSLFokusException { this.fmlBuffer[78].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_BL_COMPLT_DATE() throws BSLFokusException { return ((String) this.fmlBuffer[79].getValue(0)); }
	public void set_BL_COMPLT_DATE(String value) throws BSLFokusException { this.fmlBuffer[79].setValue(0, value); }


	public Integer get_BL_SPECIAL_CYCLE() throws BSLFokusException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[80].getValue(0))); }
	public void set_BL_SPECIAL_CYCLE(Integer value) throws BSLFokusException { this.fmlBuffer[80].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_BL_SPECL_CYCL_TYPE() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[81].getValue(0))); }
	public void set_BL_SPECL_CYCL_TYPE(String value) throws BSLFokusException { this.fmlBuffer[81].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_BL_PRT_CATEGORY() throws BSLFokusException { return ((String) this.fmlBuffer[82].getValue(0)); }
	public void set_BL_PRT_CATEGORY(String value) throws BSLFokusException { this.fmlBuffer[82].setValue(0, value); }


	public String get_BL_ZERO_BALANC_IND() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[83].getValue(0))); }
	public void set_BL_ZERO_BALANC_IND(String value) throws BSLFokusException { this.fmlBuffer[83].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_BL_MAN_HNDL_RSN() throws BSLFokusException { return ((String) this.fmlBuffer[84].getValue(0)); }
	public void set_BL_MAN_HNDL_RSN(String value) throws BSLFokusException { this.fmlBuffer[84].setValue(0, value); }


	public String get_BL_MAN_HNDL_EFF_DATE() throws BSLFokusException { return ((String) this.fmlBuffer[85].getValue(0)); }
	public void set_BL_MAN_HNDL_EFF_DATE(String value) throws BSLFokusException { this.fmlBuffer[85].setValue(0, value); }


	public String get_BL_MAN_HNDL_EXP_DATE() throws BSLFokusException { return ((String) this.fmlBuffer[86].getValue(0)); }
	public void set_BL_MAN_HNDL_EXP_DATE(String value) throws BSLFokusException { this.fmlBuffer[86].setValue(0, value); }


	public Integer get_BL_MAN_HNDL_REQ_OPID() throws BSLFokusException { return ((Integer) this.fmlBuffer[87].getValue(0)); }
	public void set_BL_MAN_HNDL_REQ_OPID(Integer value) throws BSLFokusException { this.fmlBuffer[87].setValue(0, value); }


	public Integer get_BL_MAN_HNDL_BY_OPID() throws BSLFokusException { return ((Integer) this.fmlBuffer[88].getValue(0)); }
	public void set_BL_MAN_HNDL_BY_OPID(Integer value) throws BSLFokusException { this.fmlBuffer[88].setValue(0, value); }


	public String get_BL_REQ_ST_GRACE_PRD() throws BSLFokusException { return ((String) this.fmlBuffer[89].getValue(0)); }
	public void set_BL_REQ_ST_GRACE_PRD(String value) throws BSLFokusException { this.fmlBuffer[89].setValue(0, value); }


	public String get_BL_REQ_END_GRACE_PRD() throws BSLFokusException { return ((String) this.fmlBuffer[90].getValue(0)); }
	public void set_BL_REQ_END_GRACE_PRD(String value) throws BSLFokusException { this.fmlBuffer[90].setValue(0, value); }


	public Integer get_BL_NEXT_CYCLE() throws BSLFokusException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[91].getValue(0))); }
	public void set_BL_NEXT_CYCLE(Integer value) throws BSLFokusException { this.fmlBuffer[91].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_BL_NEXT_CYC_EFF_DATE() throws BSLFokusException { return ((String) this.fmlBuffer[92].getValue(0)); }
	public void set_BL_NEXT_CYC_EFF_DATE(String value) throws BSLFokusException { this.fmlBuffer[92].setValue(0, value); }


	public String get_BL_SUSP_RC_RATE_TYPE() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[93].getValue(0))); }
	public void set_BL_SUSP_RC_RATE_TYPE(String value) throws BSLFokusException { this.fmlBuffer[93].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_BL_DEF_MAILING_IND() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[94].getValue(0))); }
	public void set_BL_DEF_MAILING_IND(String value) throws BSLFokusException { this.fmlBuffer[94].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_BL_BILL_PROD_IND() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[95].getValue(0))); }
	public void set_BL_BILL_PROD_IND(String value) throws BSLFokusException { this.fmlBuffer[95].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_BL_BAL_HANDLE_IND() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[96].getValue(0))); }
	public void set_BL_BAL_HANDLE_IND(String value) throws BSLFokusException { this.fmlBuffer[96].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_BL_UD_LST_PROD_DATE() throws BSLFokusException { return ((String) this.fmlBuffer[97].getValue(0)); }
	public void set_BL_UD_LST_PROD_DATE(String value) throws BSLFokusException { this.fmlBuffer[97].setValue(0, value); }


	public Integer get_BL_UD_LST_CYC_RUN_YR() throws BSLFokusException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[98].getValue(0))); }
	public void set_BL_UD_LST_CYC_RUN_YR(Integer value) throws BSLFokusException { this.fmlBuffer[98].setValue(0, TypeConverter.integerToShort(value)); }


	public Integer get_BL_UD_LST_CYC_RUN_MN() throws BSLFokusException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[99].getValue(0))); }
	public void set_BL_UD_LST_CYC_RUN_MN(Integer value) throws BSLFokusException { this.fmlBuffer[99].setValue(0, TypeConverter.integerToShort(value)); }


	public Integer get_BL_UD_LST_RG_BL_SEQNO() throws BSLFokusException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[100].getValue(0))); }
	public void set_BL_UD_LST_RG_BL_SEQNO(Integer value) throws BSLFokusException { this.fmlBuffer[100].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_BL_UD_LST_RG_CYC_DATE() throws BSLFokusException { return ((String) this.fmlBuffer[101].getValue(0)); }
	public void set_BL_UD_LST_RG_CYC_DATE(String value) throws BSLFokusException { this.fmlBuffer[101].setValue(0, value); }


	public Integer get_BL_UD_LST_CYC_CD() throws BSLFokusException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[102].getValue(0))); }
	public void set_BL_UD_LST_CYC_CD(Integer value) throws BSLFokusException { this.fmlBuffer[102].setValue(0, TypeConverter.integerToShort(value)); }


	public Integer get_BL_UD_SPCL_CYC() throws BSLFokusException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[103].getValue(0))); }
	public void set_BL_UD_SPCL_CYC(Integer value) throws BSLFokusException { this.fmlBuffer[103].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_BL_UD_SPCL_CYC_TYPE() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[104].getValue(0))); }
	public void set_BL_UD_SPCL_CYC_TYPE(String value) throws BSLFokusException { this.fmlBuffer[104].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_BL_NO_MNSP_IND() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[105].getValue(0))); }
	public void set_BL_NO_MNSP_IND(String value) throws BSLFokusException { this.fmlBuffer[105].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_BL_LST_BAN_DIS_DT() throws BSLFokusException { return ((String) this.fmlBuffer[106].getValue(0)); }
	public void set_BL_LST_BAN_DIS_DT(String value) throws BSLFokusException { this.fmlBuffer[106].setValue(0, value); }


	public String get_BL_LST_HIER_DIS_DT() throws BSLFokusException { return ((String) this.fmlBuffer[107].getValue(0)); }
	public void set_BL_LST_HIER_DIS_DT(String value) throws BSLFokusException { this.fmlBuffer[107].setValue(0, value); }


	public String get_BL_LST_TREE_DIS_DT() throws BSLFokusException { return ((String) this.fmlBuffer[108].getValue(0)); }
	public void set_BL_LST_TREE_DIS_DT(String value) throws BSLFokusException { this.fmlBuffer[108].setValue(0, value); }


	public String get_BL_LST_BAN_DIS_DT_U() throws BSLFokusException { return ((String) this.fmlBuffer[109].getValue(0)); }
	public void set_BL_LST_BAN_DIS_DT_U(String value) throws BSLFokusException { this.fmlBuffer[109].setValue(0, value); }


	public String get_BL_LST_HIER_DIS_DT_U() throws BSLFokusException { return ((String) this.fmlBuffer[110].getValue(0)); }
	public void set_BL_LST_HIER_DIS_DT_U(String value) throws BSLFokusException { this.fmlBuffer[110].setValue(0, value); }


	public String get_BL_LST_TREE_DIS_DT_U() throws BSLFokusException { return ((String) this.fmlBuffer[111].getValue(0)); }
	public void set_BL_LST_TREE_DIS_DT_U(String value) throws BSLFokusException { this.fmlBuffer[111].setValue(0, value); }


	public Integer get_BL_LST_BAN_DIS_SN() throws BSLFokusException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[112].getValue(0))); }
	public void set_BL_LST_BAN_DIS_SN(Integer value) throws BSLFokusException { this.fmlBuffer[112].setValue(0, TypeConverter.integerToShort(value)); }


	public Integer get_BL_LST_HIER_DIS_SN() throws BSLFokusException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[113].getValue(0))); }
	public void set_BL_LST_HIER_DIS_SN(Integer value) throws BSLFokusException { this.fmlBuffer[113].setValue(0, TypeConverter.integerToShort(value)); }


	public Integer get_BL_LST_TREE_DIS_SN() throws BSLFokusException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[114].getValue(0))); }
	public void set_BL_LST_TREE_DIS_SN(Integer value) throws BSLFokusException { this.fmlBuffer[114].setValue(0, TypeConverter.integerToShort(value)); }


	public Integer get_BL_LST_BAN_DIS_SN_U() throws BSLFokusException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[115].getValue(0))); }
	public void set_BL_LST_BAN_DIS_SN_U(Integer value) throws BSLFokusException { this.fmlBuffer[115].setValue(0, TypeConverter.integerToShort(value)); }


	public Integer get_BL_LST_HIER_DIS_SN_U() throws BSLFokusException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[116].getValue(0))); }
	public void set_BL_LST_HIER_DIS_SN_U(Integer value) throws BSLFokusException { this.fmlBuffer[116].setValue(0, TypeConverter.integerToShort(value)); }


	public Integer get_BL_LST_TREE_DIS_SN_U() throws BSLFokusException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[117].getValue(0))); }
	public void set_BL_LST_TREE_DIS_SN_U(Integer value) throws BSLFokusException { this.fmlBuffer[117].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_BL_HIER_BAN_IND() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[118].getValue(0))); }
	public void set_BL_HIER_BAN_IND(String value) throws BSLFokusException { this.fmlBuffer[118].setValue(0, TypeConverter.stringToByte(value)); }


	public Integer get_BL_DUE_DAY() throws BSLFokusException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[119].getValue(0))); }
	public void set_BL_DUE_DAY(Integer value) throws BSLFokusException { this.fmlBuffer[119].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_BL_PREPAYMENT_IND() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[120].getValue(0))); }
	public void set_BL_PREPAYMENT_IND(String value) throws BSLFokusException { this.fmlBuffer[120].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_BLACK_LISTED_IND() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[121].getValue(0))); }
	public void set_BLACK_LISTED_IND(String value) throws BSLFokusException { this.fmlBuffer[121].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_VIP_IND() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[122].getValue(0))); }
	public void set_VIP_IND(String value) throws BSLFokusException { this.fmlBuffer[122].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_ORG_CODE() throws BSLFokusException { return ((String) this.fmlBuffer[123].getValue(0)); }
	public void set_ORG_CODE(String value) throws BSLFokusException { this.fmlBuffer[123].setValue(0, value); }


	public Integer get_CYCLE_FREQUENCY() throws BSLFokusException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[124].getValue(0))); }
	public void set_CYCLE_FREQUENCY(Integer value) throws BSLFokusException { this.fmlBuffer[124].setValue(0, TypeConverter.integerToShort(value)); }


	public Integer get_CYCLE_FIRST_BILL_MONTH() throws BSLFokusException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[125].getValue(0))); }
	public void set_CYCLE_FIRST_BILL_MONTH(Integer value) throws BSLFokusException { this.fmlBuffer[125].setValue(0, TypeConverter.integerToShort(value)); }


	public Double get_EDI_LOCATION_NUMBER() throws BSLFokusException { return ((Double) this.fmlBuffer[126].getValue(0)); }
	public void set_EDI_LOCATION_NUMBER(Double value) throws BSLFokusException { this.fmlBuffer[126].setValue(0, value); }


	public Integer get_CS_MIN_REQ_CTNS() throws BSLFokusException { return ((Integer) this.fmlBuffer[127].getValue(0)); }
	public void set_CS_MIN_REQ_CTNS(Integer value) throws BSLFokusException { this.fmlBuffer[127].setValue(0, value); }


	public Double get_CS_PEN_PER_MISS_CTN() throws BSLFokusException { return ((Double) this.fmlBuffer[128].getValue(0)); }
	public void set_CS_PEN_PER_MISS_CTN(Double value) throws BSLFokusException { this.fmlBuffer[128].setValue(0, value); }


	public String get_CS_COM_START_DATE() throws BSLFokusException { return ((String) this.fmlBuffer[129].getValue(0)); }
	public void set_CS_COM_START_DATE(String value) throws BSLFokusException { this.fmlBuffer[129].setValue(0, value); }


	public String get_CS_COM_END_DATE() throws BSLFokusException { return ((String) this.fmlBuffer[130].getValue(0)); }
	public void set_CS_COM_END_DATE(String value) throws BSLFokusException { this.fmlBuffer[130].setValue(0, value); }


	public String get_CS_COM_REASON_CODE() throws BSLFokusException { return ((String) this.fmlBuffer[131].getValue(0)); }
	public void set_CS_COM_REASON_CODE(String value) throws BSLFokusException { this.fmlBuffer[131].setValue(0, value); }


	public Integer get_CS_COM_ORIG_NO_MONTH() throws BSLFokusException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[132].getValue(0))); }
	public void set_CS_COM_ORIG_NO_MONTH(Integer value) throws BSLFokusException { this.fmlBuffer[132].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_CS_FOLLOW_UPS_STATE() throws BSLFokusException { return ((String) this.fmlBuffer[133].getValue(0)); }
	public void set_CS_FOLLOW_UPS_STATE(String value) throws BSLFokusException { this.fmlBuffer[133].setValue(0, value); }


	public String get_CS_SPEC_MEMO_IND() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[134].getValue(0))); }
	public void set_CS_SPEC_MEMO_IND(String value) throws BSLFokusException { this.fmlBuffer[134].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_STATUS_ISSUE_DATE() throws BSLFokusException { return ((String) this.fmlBuffer[135].getValue(0)); }
	public void set_STATUS_ISSUE_DATE(String value) throws BSLFokusException { this.fmlBuffer[135].setValue(0, value); }


	public String get_CS_BAN_TRX_OFF_IND() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[136].getValue(0))); }
	public void set_CS_BAN_TRX_OFF_IND(String value) throws BSLFokusException { this.fmlBuffer[136].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_CS_HANDLE_BY_CTN_IND() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[137].getValue(0))); }
	public void set_CS_HANDLE_BY_CTN_IND(String value) throws BSLFokusException { this.fmlBuffer[137].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_CS_LOCK_MECHANISM() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[138].getValue(0))); }
	public void set_CS_LOCK_MECHANISM(String value) throws BSLFokusException { this.fmlBuffer[138].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_CS_DEF_PRODUCT_TYPE() throws BSLFokusException { return ((String) this.fmlBuffer[139].getValue(0)); }
	public void set_CS_DEF_PRODUCT_TYPE(String value) throws BSLFokusException { this.fmlBuffer[139].setValue(0, value); }


	public Double get_CAS_DEP_AMT_PER_CTN() throws BSLFokusException { return ((Double) this.fmlBuffer[140].getValue(0)); }
	public void set_CAS_DEP_AMT_PER_CTN(Double value) throws BSLFokusException { this.fmlBuffer[140].setValue(0, value); }


	public Integer get_CONV_RUN_NO() throws BSLFokusException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[141].getValue(0))); }
	public void set_CONV_RUN_NO(Integer value) throws BSLFokusException { this.fmlBuffer[141].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_CARRY_OVER_BILL() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[142].getValue(0))); }
	public void set_CARRY_OVER_BILL(String value) throws BSLFokusException { this.fmlBuffer[142].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_OLD_ACCOUNT_ID() throws BSLFokusException { return ((String) this.fmlBuffer[143].getValue(0)); }
	public void set_OLD_ACCOUNT_ID(String value) throws BSLFokusException { this.fmlBuffer[143].setValue(0, value); }


	public String get_HIDE_PHONE_DIGITS_IND() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[144].getValue(0))); }
	public void set_HIDE_PHONE_DIGITS_IND(String value) throws BSLFokusException { this.fmlBuffer[144].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_SEC_DEPARTMENT() throws BSLFokusException { return ((String) this.fmlBuffer[145].getValue(0)); }
	public void set_SEC_DEPARTMENT(String value) throws BSLFokusException { this.fmlBuffer[145].setValue(0, value); }


	public String get_PAYABLE_LTR_SEND_DATE() throws BSLFokusException { return ((String) this.fmlBuffer[146].getValue(0)); }
	public void set_PAYABLE_LTR_SEND_DATE(String value) throws BSLFokusException { this.fmlBuffer[146].setValue(0, value); }


	public Integer get_NEXT_CONF_ROOT_BAN() throws BSLFokusException { return ((Integer) this.fmlBuffer[147].getValue(0)); }
	public void set_NEXT_CONF_ROOT_BAN(Integer value) throws BSLFokusException { this.fmlBuffer[147].setValue(0, value); }


	public String get_LAST_CONF_DATE() throws BSLFokusException { return ((String) this.fmlBuffer[148].getValue(0)); }
	public void set_LAST_CONF_DATE(String value) throws BSLFokusException { this.fmlBuffer[148].setValue(0, value); }


	public String get_ALLOW_ADVERTISING_IND() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[149].getValue(0))); }
	public void set_ALLOW_ADVERTISING_IND(String value) throws BSLFokusException { this.fmlBuffer[149].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_AGENCY_REF_NO() throws BSLFokusException { return ((String) this.fmlBuffer[150].getValue(0)); }
	public void set_AGENCY_REF_NO(String value) throws BSLFokusException { this.fmlBuffer[150].setValue(0, value); }


	public String get_COL_AGENCY_CONF_DT() throws BSLFokusException { return ((String) this.fmlBuffer[151].getValue(0)); }
	public void set_COL_AGENCY_CONF_DT(String value) throws BSLFokusException { this.fmlBuffer[151].setValue(0, value); }


	public String get_BAN_GROUP_NO() throws BSLFokusException { return ((String) this.fmlBuffer[152].getValue(0)); }
	public void set_BAN_GROUP_NO(String value) throws BSLFokusException { this.fmlBuffer[152].setValue(0, value); }


	public String get_CAAP_TYPE() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[153].getValue(0))); }
	public void set_CAAP_TYPE(String value) throws BSLFokusException { this.fmlBuffer[153].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_BAN_FF_EXP_DATE() throws BSLFokusException { return ((String) this.fmlBuffer[154].getValue(0)); }
	public void set_BAN_FF_EXP_DATE(String value) throws BSLFokusException { this.fmlBuffer[154].setValue(0, value); }


	public Double get_UNBILLED_REVENUE() throws BSLFokusException { return ((Double) this.fmlBuffer[155].getValue(0)); }
	public void set_UNBILLED_REVENUE(Double value) throws BSLFokusException { this.fmlBuffer[155].setValue(0, value); }


	public String get_LAST_AGNCY_UPDATE() throws BSLFokusException { return ((String) this.fmlBuffer[156].getValue(0)); }
	public void set_LAST_AGNCY_UPDATE(String value) throws BSLFokusException { this.fmlBuffer[156].setValue(0, value); }


	public String get_WAIVER_RSN_CODE() throws BSLFokusException { return ((String) this.fmlBuffer[157].getValue(0)); }
	public void set_WAIVER_RSN_CODE(String value) throws BSLFokusException { this.fmlBuffer[157].setValue(0, value); }


	public String get_COL_WAIVER_EXP_DATE() throws BSLFokusException { return ((String) this.fmlBuffer[158].getValue(0)); }
	public void set_COL_WAIVER_EXP_DATE(String value) throws BSLFokusException { this.fmlBuffer[158].setValue(0, value); }


	public String get_INVOICE_FEE_WAIVE_IND() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[159].getValue(0))); }
	public void set_INVOICE_FEE_WAIVE_IND(String value) throws BSLFokusException { this.fmlBuffer[159].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_PRD_ZERO_RATE_BILL() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[160].getValue(0))); }
	public void set_PRD_ZERO_RATE_BILL(String value) throws BSLFokusException { this.fmlBuffer[160].setValue(0, TypeConverter.stringToByte(value)); }


	public Integer get_BL_INV_SEQ_NO() throws BSLFokusException { return (TypeConverter.shortToInteger((Short) this.fmlBuffer[161].getValue(0))); }
	public void set_BL_INV_SEQ_NO(Integer value) throws BSLFokusException { this.fmlBuffer[161].setValue(0, TypeConverter.integerToShort(value)); }


	public String get_BRAND_ID() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[162].getValue(0))); }
	public void set_BRAND_ID(String value) throws BSLFokusException { this.fmlBuffer[162].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_HELD_SUB_LETTER_IND() throws BSLFokusException { return (TypeConverter.byteToString((Byte) this.fmlBuffer[163].getValue(0))); }
	public void set_HELD_SUB_LETTER_IND(String value) throws BSLFokusException { this.fmlBuffer[163].setValue(0, TypeConverter.stringToByte(value)); }


	public String get_HELD_SUB_LTR_EXP_DATE() throws BSLFokusException { return ((String) this.fmlBuffer[164].getValue(0)); }
	public void set_HELD_SUB_LTR_EXP_DATE(String value) throws BSLFokusException { this.fmlBuffer[164].setValue(0, value); }


	public String get_CURRENCY_TYPE() throws BSLFokusException { return ((String) this.fmlBuffer[165].getValue(0)); }
	public void set_CURRENCY_TYPE(String value) throws BSLFokusException { this.fmlBuffer[165].setValue(0, value); }


	public String get_COUNTERPART_ID() throws BSLFokusException { return ((String) this.fmlBuffer[166].getValue(0)); }
	public void set_COUNTERPART_ID(String value) throws BSLFokusException { this.fmlBuffer[166].setValue(0, value); }



} // ArGtBanOutput
