
package com.bsl.exceptions;



import java.util.Date;

/**
 * The ancestor of all Tuxedo-related exceptions.
 *
 * @author Ninja Team
 * @version 6.0
 * @netcom.fokusref
 */
public class BSLFokusException extends Exception {
    /**
     *
     */
    private static final long serialVersionUID = -5486012879148228463L;
    /**
     * Used to hold an error code returned by the BEA Tuxedo subsystem.
     */
    private int code = 0;
    private Date date = null;

    /**
     * @param msg
     * @roseuid 3D6611E101E2
     */
    public BSLFokusException(String msg) {

        this.code = 0;
    }

    /**
     * @param errorCode the code to set on this exception
     * @param msg
     * @roseuid 3D64F32E035A
     */
    public BSLFokusException(final int errorCode, String msg) {

        this.code = 0;
    }

    /**
     * @param code
     * @param msg
     * @roseuid 3D64F32E035A
     */
    public BSLFokusException(String msg, int code) {

        this.code = code;
    }
    
    /**
     * Retrieves the Tuxedo-specific error code generated by the BEA Tuxedo subsystem.
     *
     * @return int
     * @netcom.fokusref
     * @roseuid 3D64F10D00C5
     */
    public int getCode() {
        return this.code;
    }

    /**
     * @return java.util.Date
     * @roseuid 3D661D8F0245
     */
    public Date getDate() {
        return this.date;
    }

    /**
     * @param date
     * @roseuid 3D661D8F0264
     */
    public void setDate(Date date) {
        this.date = date;
    }
}
